receivers:
  kafka/metrics:
    brokers:
      - broker:29092
    protocol_version: 2.0.0
    topic: metrics_topic
  #    encoding: raw
  kafka/trace:
    brokers:
      - broker:29092
    protocol_version: 2.0.0
    topic: traces_topic
    encoding: jaeger_json

processors:
  batch:
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  influxdb:
    endpoint: http://influxdb:8086
    timeout: 500ms
    org: obs-org
    bucket: observation
    token: MyInitialAdminToken0==
    span_dimensions:
      - service.name
      - span.name
    log_record_dimensions:
      - service.name
    metrics_schema: telegraf-prometheus-v1

    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  pipelines:
    traces:
      receivers: [kafka/trace]
      processors: []
      exporters: [otlp/jaeger]
    metrics:
      receivers: [kafka/metrics]
      processors: []
      exporters: [influxdb]